# Generated by Django 2.1.3 on 2018-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        ('service', '0001_initial'),
        ('sphere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('link', models.CharField(default='', max_length=255, verbose_name='Ссылка на кейс')),
                ('product_link', models.CharField(default='', max_length=255, verbose_name='Ссылка на продукт')),
                ('logo', models.ImageField(upload_to='cases/%Y/%m/%d/', verbose_name='Лого')),
                ('preview_picture', models.ImageField(upload_to='cases/%Y/%m/%d/', verbose_name='Превьешка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('services', models.ManyToManyField(related_name='cases', to='service.Service', verbose_name='Услуги')),
                ('spheres', models.ManyToManyField(related_name='cases', to='sphere.Sphere', verbose_name='Отрасли')),
                ('technologies', models.ManyToManyField(related_name='cases', to='technology.Technology', verbose_name='Технологии')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
    ]
