# Generated by Django 2.1.3 on 2018-11-14 13:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Описание'),
        ),
    ]
