# Generated by Django 2.1.3 on 2018-11-15 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20181115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 12, 4, 256060), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 11, 12, 4, 256033), verbose_name='Дата старта'),
        ),
    ]
