# Generated by Django 2.1.3 on 2018-11-15 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20181115_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='case',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 15, 34, 10, 293076), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 15, 34, 10, 293046), verbose_name='Дата старта'),
        ),
    ]
